### ISSUE TITLE
Promises are not being reported correctly

### ISSUE THREAD

**Issue by luismendozamx** [twokul/ember-cli-bugsnag#19] opened 2015-06-05 17:57 UTC
This might not be an issue and maybe it's something I did wrong. We installed bugsnag a couple weeks ago and our app has been reporting errors regularly, both on production and our staging server. But none of them have been due to error caused by unfulfilled promises. And I'm pretty sure we have a few of those.

This is the stacktrace generated by an error in bugsnag right after Ember triggers and exception on RSVP when our api responds with a 500. It's really hard to debug due to the assets being minified.

![screen shot 2015-06-05 at 12 54 09 pm](https://cloud.githubusercontent.com/assets/5739945/8011868/3cbd433a-0b82-11e5-8a2a-2a35224266e5.png)

Any clue on how to solve it?

**Comment by twokul** [comment] 2015-06-05 23:08
@luismendozamx I'd be more than happy to jump on a hangout with you to help to troubleshoot. this addon doesn't do anything magical, merely reports error that it gets. we might be able to look at unfulfilled promises `_details` and add them to the info to send to Bugsnag.

**Comment by ZackMattor** [comment] 2016-01-07 18:58
Kinda related to this... the new version of ember throws RSVP errors when you overwrite a transition in progress... its kind of annoying to get bug snags for expected behavior... im not sure how to solve it though.

**Comment by gertjanwytynck** [comment] 2016-03-16 19:09
Hi @luismendozamx, did you fixed this problem? Or do you have a workaround, same issue here.

**Comment by binhums** [comment] 2016-03-30 18:53
Hi @gertjanwytynck, there have been some recent changes to the way we do the reporting so I'd be surprised if it is the same issue.

I'd like to get this closed off though. I am seeing `Adapter operation failed` make it through to Bugsnag in production.

Is the specific reproduction step to return a 500?

**Comment by kcin1018** [comment] 2016-05-10 02:43
I am not sure which version of Ember you are using but you can hook into the Ember.RSVP error callback:

https://guides.emberjs.com/v2.5.0/configuring-ember/debugging/ (towards the bottom)

```
Ember.RSVP.on('error', function(error) {
  Ember.Logger.assert(false, error);
});
```

**Comment by binhums** [comment] 2016-05-10 02:57
I'm going to close this issue, @gertjanwytynck @luismendozamx if you're still having problems holler at me. More than happy to work together on your issues.

**Closed by binhums** 2016-05-10 02:57 UTC

**Comment by timiyay** [comment] 2016-08-15 01:43
I'm having a similar issue now.

It appears this project doesn't listen for `Ember.RSVP.on('error', ...)`, so promises aren't reported to Bugsnag.

This Raygun article is a good starting point for the 3 error listener hooks I'll be supporting: https://raygun.com/blog/2015/01/javascript-error-handling-ember-js/

We've got 1 out of 3 in this library ATM.

**Comment by binhums** [comment] 2016-08-15 09:18
@timiyay we actually used to do that, the article code looks exactly like code we used to have. I had been convinced that in recent versions of Ember the onerror call is enough for these cases.

That might not actually be the case. What version of Ember are you using?

https://github.com/binhums/ember-cli-bugsnag/commit/6e87f7aebccecf1c9d5ac0059ca023c1e2b9a25f

Either way I think we should be backwards compatible if it is our intention to pick up promise errors.

In the context of my own apps I would track promise errors at the backend (e.g. a 500 is important, a 404 probably isn't). That said this thread makes it clear that some people do want to track this, so this could be a configurable setting.

**Comment by binhums** [comment] 2016-08-16 10:07
Ok I've just tested this against master and the branch I'm planning to merge. It looks like both are reporting a promise error for 404s (which is probably undesirable unless actually asked for).

![image](https://cloud.githubusercontent.com/assets/831043/17695658/82dcaf86-63a1-11e6-9b5f-9434a0381c19.png)

Admittedly this is testing against Ember 2.8.0 beta but I think in recent versions Ember.Error has been improved to include this kind of error. What version of Ember are you using @timiyay?

**Comment by timiyay** [comment] 2016-08-16 11:09
@binhums I was on Ember 2.7.0. Happy to skip it, if you're finding it being logged twice. I'm still learning re: Promise exception handling, so I may have misunderstood the issue.
